language: rust
rust:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test -- --nocapture

branches:
  only:
    - master

notifications:
  email:
    on_success: never
